### ISSUE TITLE
Suggested Readme edits

### ISSUE THREAD

**Issue by adam-cornwell** [Thakar-Lab/BONITA-Python3#2]
Hi, in the readme, `conda env create –name=BONITA --file platform_BONITA.yaml` should be --name. I also noticed that the YAML file currently has windows line endings and has a user-specific prefix set, so it might be good to remove that prefix (or mention that the YAML might need to be edited).

**Comment by muktapalshikar** [comment]
Noted - will fix!

**Comment by muktapalshikar** [comment]
The readme was edited and a new version of platform_BONITA.yaml uploaded. Thanks @adam-cornwell !
